### ISSUE TITLE
What line in journal causes an exception?

### ISSUE THREAD

**Issue by RidaAyed** [glasserc/ledger-to-beancount#13]
Hi

Testing with two journals, one is converted while the other one causes an exception. However, reading the trace below I'm not able to understand, which line in journal is the cause?

`$ ledger-to-beancount ~/journal.txt`
```
Traceback (most recent call last):
  File "/home/ra/.local/share/virtualenvs/ledger-to-beancount-524C-Oyj/bin/ledger-to-beancount", line 11, in <module>
    sys.exit(main())
  File "/home/ra/.local/share/virtualenvs/ledger-to-beancount-524C-Oyj/lib/python3.6/site-packages/ledger_to_beancount/__main__.py", line 7, in main
    output = translate_file(open(filename).readlines())
  File "/home/ra/.local/share/virtualenvs/ledger-to-beancount-524C-Oyj/lib/python3.6/site-packages/ledger_to_beancount/__init__.py", line 223, in translate_file
    posting = '  {}        {}'.format(account, translate_amount(rest))
  File "/home/ra/.local/share/virtualenvs/ledger-to-beancount-524C-Oyj/lib/python3.6/site-packages/ledger_to_beancount/__init__.py", line 126, in translate_amount
    (amount, units) = parse_amount_and_units(amount)
TypeError: 'NoneType' object is not iterable
```

**Comment by glasserc** [comment]
Unfortunately, exceptions like this don't indicate the line number, just that some bug was hit somewhere and what the program was doing when it realized something went wrong. From looking at the code, it looks like my code doesn't handle the case where an amount doesn't have a space in it, so you could look for that. It would probably be good to add code to detect exceptions like this and print the line number we were processing at the time. PRs welcome :)
